version: "3.9"

services:
  postgres_test:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sync_user
      POSTGRES_PASSWORD: sync_admin
      POSTGRES_DB: sync_test_db
    ports:
      - "55432:5432"
    volumes:
      - sync_test_pg_data:/var/lib/postgresql/data

  redis_test:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "56379:6379"
    volumes:
      - sync_test_redis_data:/data

volumes:
  sync_test_pg_data:
  sync_test_redis_data:

